apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofil
  labels:
    app: userprofil
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userprofil
  template:
    metadata:
      labels:
        app: userprofil
    spec:
      containers:
      - name: userprofil
        image: registrybrz6946.azurecr.io/tripinsights/userprofile:1.0
        env :
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: SQL_SERVER
          value: "sqlserverbrz6946.database.windows.net"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-userprofil

  labels:
    app: userprofil
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: userprofil
