apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  labels:
    app: userapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
      - name: userapi
        image: registrybrz6946.azurecr.io/tripinsights/userapi:1.0
        env :
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: SQL_SERVER
          value: "sqlserverbrz6946.database.windows.net"
        
        ports:
        - containerPort: 80

            
---
apiVersion: v1
kind: Service
metadata:
  name: svc-userapi
  labels:
    app: userapi
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: userapi