apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api
  name: api-dev-role
rules:
- apiGroups: [""]
  resources: ["pods","services","deployments"]
  verbs: ["*"]
  
kind: Role
metadata:
  namespace: web
  name: api-dev-role
rules:
- apiGroups: [""]
  resources: ["pods","services","deployments"]
  verbs: ["get", "watch", "list"]
  
kind: Role
metadata:
  namespace: web
  name: web-dev-role
rules:
- apiGroups: [""]
  resources: ["pods","services","deployments"]
  verbs: ["*"]
  
kind: Role
metadata:
  namespace: api
  name: web-dev-role
rules:
- apiGroups: [""]
  resources: ["pods","services","deployments"]
  verbs: ["get", "watch", "list"]

---

kind: RoleBinding
metadata:
  name: api-dev-rolebinding
  namespace: api
subjects:
- kind: User
  name: apidev@msftopenhack7003ops.onmicrosoft.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: api-dev-role
  apiGroup: rbac.authorization.k8s.io  

kind: RoleBinding
metadata:
  name: api-dev-rolebinding
  namespace: web
subjects:
- kind: User
  name: apidev@msftopenhack7003ops.onmicrosoft.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: api-dev-role
  apiGroup: rbac.authorization.k8s.io  

kind: RoleBinding
metadata:
  name: web-dev-rolebinding
  namespace: web
subjects:
- kind: User
  name: webdev@msftopenhack7003ops.onmicrosoft.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: web-dev-role
  apiGroup: rbac.authorization.k8s.io  

kind: RoleBinding
metadata:
  name: web-dev-rolebinding
  namespace: web
subjects:
- kind: User
  name: webdev@msftopenhack7003ops.onmicrosoft.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: web-dev-role
  apiGroup: rbac.authorization.k8s.io  
  