apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api
  name: api-dev-role
rules:
- apiGroups: [""]
  resources: ["pods","services","deployments"]
  verbs: ["*"]
  
kind: Role
metadata:
  namespace: web
  name: api-dev-role
rules:
- apiGroups: [""]
  resources: ["pods","services","deployments"]
  verbs: ["get", "watch", "list"]
  
kind: Role
metadata:
  namespace: web
  name: web-dev-role
rules:
- apiGroups: [""]
  resources: ["pods","services","deployments"]
  verbs: ["*"]
  
kind: Role
metadata:
  namespace: api
  name: web-dev-role
rules:
- apiGroups: [""]
  resources: ["pods","services","deployments"]
  verbs: ["get", "watch", "list"]

---

kind: RoleBinding
metadata:
  name: api-dev-rolebinding
  namespace: api
subjects:
- kind: Group
  name: 4493a5c8-b4ef-4534-b898-3e3806c86e9c
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: api-dev-role
  apiGroup: rbac.authorization.k8s.io  

kind: RoleBinding
metadata:
  name: api-dev-rolebinding
  namespace: web
subjects:
- kind: Group
  name: 4493a5c8-b4ef-4534-b898-3e3806c86e9c
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: api-dev-role
  apiGroup: rbac.authorization.k8s.io  

kind: RoleBinding
metadata:
  name: web-dev-rolebinding
  namespace: web
subjects:
- kind: Group
  name: 2b3b57cd-6f01-4ed4-b02b-4dd9ad125810
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: web-dev-role
  apiGroup: rbac.authorization.k8s.io  

kind: RoleBinding
metadata:
  name: web-dev-rolebinding
  namespace: web
subjects:
- kind: Group
  name: 2b3b57cd-6f01-4ed4-b02b-4dd9ad125810
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: web-dev-role
  apiGroup: rbac.authorization.k8s.io  
  