apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripwiewer
  labels:
    app: tripwiewer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripwiewer
  template:
    metadata:
      labels:
        app: tripwiewer
    spec:
      containers:
      - name: tripwiewer
        image: registrybrz6946.azurecr.io/tripinsights/trip_viewer:1.0
        ports:
        - containerPort: 80
        env :
        - name: USERPROFILE_API_ENDPOINT
          value: "http://svc-userprofil.api.svc.cluster.local"
        - name: TRIPS_API_ENDPOINT
          value: "http://trip-api.api.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: front-tripwiewer
  labels:
    app: tripwiewer
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: tripwiewer
  type: LoadBalancer