apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripwiewer
  labels:
    app: tripwiewer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripwiewer
  template:
    metadata:
      labels:
        app: tripwiewer
    spec:
      containers:
      - name: tripwiewer
        image: registrybrz6946.azurecr.io/tripinsights/trip_viewer:1.0
        ports:
        - containerPort: 80