apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/trips
        pathType: Prefix
        backend:
          service:
            name: trip-api
            port:
              number: 80
      - path: /api/docs/trips
        pathType: Prefix
        backend:
          service:
            name: trip-api
            port:
              number: 80
      - path: /api/json
        pathType: Prefix
        backend:
          service:
            name: trip-api
            port:
              number: 80
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: trip-api
            port:
              number: 80
              
      - path: /api/user-java
        pathType: Prefix
        backend:
          service:
            name: svc-userapi
            port:
              number: 80
      - path: /api/docs/user-java
        pathType: Prefix
        backend:
          service:
            name: svc-userapi
            port:
              number: 80
      - path: /api/documentation/user-java
        pathType: Prefix
        backend:
          service:
            name: svc-userapi
            port:
              number: 80
      - path: /api/api-docs
        pathType: Prefix
        backend:
          service:
            name: svc-userapi
            port:
              number: 80
      - path: /api/metrics
        pathType: Prefix
        backend:
          service:
            name: svc-userapi
            port:
              number: 80
              
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: svc-userprofil
            port:
              number: 80
      - path: /api/docs/user
        pathType: Prefix
        backend:
          service:
            name: svc-userprofil
            port:
              number: 80
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: svc-userprofil
            port:
              number: 80
              
      - path: /api/poi
        pathType: Prefix
        backend:
          service:
            name: svc-poi
            port:
              number: 80
      - path: /api/docs/poi
        pathType: Prefix
        backend:
          service:
            name: svc-poi
            port:
              number: 80
      - path: /swagger/docs/poi
        pathType: Prefix
        backend:
          service:
            name: svc-poi
            port:
              number: 80
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: svc-poi
            port:
              number: 80