apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofil
  labels:
    app: userprofil
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userprofil
  template:
    metadata:
      labels:
        app: userprofil
    spec:
      containers:
      - name: userprofil
        image: registrybrz6946.azurecr.io/tripinsights/userprofile:1.0
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true       
        ports:
        - containerPort: 80
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-userprofil

  labels:
    app: userprofil
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: userprofil
