apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trip-api
  template:
    metadata:
      labels:
        app: trip-api
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: trip-api
        image: registrybrz6946.azurecr.io/tripinsights/trip_api:1.0
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true       
        ports:
        - containerPort: 80
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
apiVersion: v1
kind: Service
metadata:
  name: trip-api
spec:
  ports:
  - port: 80
  selector:
    app: trip-api